name: Buildm32

on:
  push:
    branches: [ "forjpegview" ]
  pull_request:
    branches: [ "forjpegview" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019
    
    # Run a job for each of the specified target architectures:
    strategy:
      matrix:
        arch:
          - win64
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Build
        continue-on-error: true
        run: |
          git submodule update --init --recursive --depth 1 --recommend-shallow
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -A Win32 ..
          msbuild.exe /p:Platform=Win32 /p:configuration="Release" LIBJXL.sln /t:jxl_dec /t:jxl_threads
      - name: moving
        run: |
          mv build/lib/Release/* build/Release
          mv build/third_party/brotli/Release/* build/Release
      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: releaselibjxl32
          path: build/Release
      # ...
